-- Tabela tenant
CREATE TABLE IF NOT EXISTS public.tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE public.tenant ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.tenant FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.tenant FOR INSERT WITH CHECK (true);

-- Tabela account
CREATE TABLE IF NOT EXISTS public.account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    username VARCHAR NOT NULL,
    password_hash VARCHAR NOT NULL,
    role VARCHAR NOT NULL DEFAULT 'operator',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ NULL
);

ALTER TABLE public.account ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.account FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.account FOR INSERT WITH CHECK (true);

-- Tabela role_permission
CREATE TABLE IF NOT EXISTS public.role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR NOT NULL,
    permission VARCHAR NOT NULL,
    allowed BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_role_permission UNIQUE (role, permission)
);

ALTER TABLE public.role_permission ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.role_permission FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.role_permission FOR INSERT WITH CHECK (true);

-- Tabela reading
CREATE TABLE IF NOT EXISTS public.reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    temperatura DOUBLE PRECISION NOT NULL,
    status VARCHAR NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.reading ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.reading FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.reading FOR INSERT WITH CHECK (true);

-- Tabela bird_snapshot
CREATE TABLE IF NOT EXISTS public.bird_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    bird_uid BIGINT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    x1 BIGINT NOT NULL,
    y1 BIGINT NOT NULL,
    x2 BIGINT NOT NULL,
    y2 BIGINT NOT NULL,
    temperatura_estimada DOUBLE PRECISION NULL,
    metodo_temperatura VARCHAR NOT NULL DEFAULT 'estimada_rgb_proxy',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.bird_snapshot ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.bird_snapshot FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.bird_snapshot FOR INSERT WITH CHECK (true);

-- Tabela bird_identity
CREATE TABLE IF NOT EXISTS public.bird_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    bird_uid BIGINT UNIQUE NOT NULL,
    first_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sightings BIGINT NOT NULL DEFAULT 0,
    max_confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    last_temp_estimada DOUBLE PRECISION NULL
);

ALTER TABLE public.bird_identity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.bird_identity FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.bird_identity FOR INSERT WITH CHECK (true);

-- Tabela bird_track_point
CREATE TABLE IF NOT EXISTS public.bird_track_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    bird_uid BIGINT NOT NULL,
    x BIGINT NOT NULL,
    y BIGINT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.bird_track_point ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.bird_track_point FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.bird_track_point FOR INSERT WITH CHECK (true);

-- Tabela event_log
CREATE TABLE IF NOT EXISTS public.event_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL DEFAULT 'galpao-1',
    event_type VARCHAR NOT NULL,
    level VARCHAR NOT NULL DEFAULT 'info',
    message VARCHAR NOT NULL,
    metadata_json TEXT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.event_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.event_log FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.event_log FOR INSERT WITH CHECK (true);

-- Tabela sensor_reading
CREATE TABLE IF NOT EXISTS public.sensor_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL DEFAULT 'galpao-1',
    temperature_c DOUBLE PRECISION NULL,
    humidity_pct DOUBLE PRECISION NULL,
    ammonia_ppm DOUBLE PRECISION NULL,
    feed_level_pct DOUBLE PRECISION NULL,
    water_level_pct DOUBLE PRECISION NULL,
    source VARCHAR NOT NULL DEFAULT 'sensor',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.sensor_reading ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.sensor_reading FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.sensor_reading FOR INSERT WITH CHECK (true);

-- Tabela batch
CREATE TABLE IF NOT EXISTS public.batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL DEFAULT 'galpao-1',
    name VARCHAR NOT NULL,
    start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    notes VARCHAR NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.batch ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.batch FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.batch FOR INSERT WITH CHECK (true);

-- Tabela weight_estimate
CREATE TABLE IF NOT EXISTS public.weight_estimate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL DEFAULT 'galpao-1',
    avg_weight_g DOUBLE PRECISION NOT NULL,
    ideal_weight_g DOUBLE PRECISION NULL,
    flock_count BIGINT NOT NULL DEFAULT 0,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    source VARCHAR NOT NULL DEFAULT 'vision_estimate',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.weight_estimate ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.weight_estimate FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.weight_estimate FOR INSERT WITH CHECK (true);

-- Tabela acoustic_reading
CREATE TABLE IF NOT EXISTS public.acoustic_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL DEFAULT 'galpao-1',
    respiratory_health_index DOUBLE PRECISION NOT NULL,
    cough_index DOUBLE PRECISION NOT NULL,
    stress_audio_index DOUBLE PRECISION NOT NULL,
    source VARCHAR NOT NULL DEFAULT 'sensor',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.acoustic_reading ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.acoustic_reading FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.acoustic_reading FOR INSERT WITH CHECK (true);

-- Tabela thermal_anomaly
CREATE TABLE IF NOT EXISTS public.thermal_anomaly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL DEFAULT 'galpao-1',
    bird_uid BIGINT NULL,
    kind VARCHAR NOT NULL,
    estimated_temp_c DOUBLE PRECISION NOT NULL,
    ambient_temp_c DOUBLE PRECISION NOT NULL,
    sector VARCHAR NULL,
    x BIGINT NULL,
    y BIGINT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.thermal_anomaly ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.thermal_anomaly FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.thermal_anomaly FOR INSERT WITH CHECK (true);

-- Tabela energy_usage_daily
CREATE TABLE IF NOT EXISTS public.energy_usage_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL DEFAULT 'galpao-1',
    day TIMESTAMPTZ NOT NULL,
    ventilacao_seconds DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    aquecedor_seconds DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.energy_usage_daily ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.energy_usage_daily FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.energy_usage_daily FOR INSERT WITH CHECK (true);

-- Tabela audit_log
CREATE TABLE IF NOT EXISTS public.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    actor VARCHAR NOT NULL DEFAULT 'system',
    action VARCHAR NOT NULL,
    source VARCHAR NOT NULL DEFAULT 'backend',
    ip VARCHAR NULL,
    details_json TEXT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.audit_log FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.audit_log FOR INSERT WITH CHECK (true);

-- Tabela sync_queue_item
CREATE TABLE IF NOT EXISTS public.sync_queue_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    item_type VARCHAR NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    synced_at TIMESTAMPTZ NULL,
    attempts BIGINT NOT NULL DEFAULT 0
);

ALTER TABLE public.sync_queue_item ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.sync_queue_item FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.sync_queue_item FOR INSERT WITH CHECK (true);

-- Tabela batch_logbook
CREATE TABLE IF NOT EXISTS public.batch_logbook (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL DEFAULT 'galpao-1',
    batch_id BIGINT NULL,
    note TEXT NOT NULL,
    author VARCHAR NOT NULL DEFAULT 'operador',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.batch_logbook ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.batch_logbook FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.batch_logbook FOR INSERT WITH CHECK (true);

-- Tabela push_token
CREATE TABLE IF NOT EXISTS public.push_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    token VARCHAR UNIQUE NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.push_token ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.push_token FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.push_token FOR INSERT WITH CHECK (true);

-- Tabela camera
CREATE TABLE IF NOT EXISTS public.camera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    camera_id VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    connection_type VARCHAR NOT NULL DEFAULT 'usb',
    connection_url VARCHAR NULL,
    status VARCHAR NOT NULL DEFAULT 'offline',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_tenant_camera UNIQUE (tenant_id, camera_id)
);

ALTER TABLE public.camera ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura anonima" ON public.camera FOR SELECT USING (true);
CREATE POLICY "Permitir insercao anonima" ON public.camera FOR INSERT WITH CHECK (true);
